### ISSUE TITLE
Componente CSS 1 - Bottone

### ISSUE THREAD

**Issue by EmanueleSabetta** [Movimento5StelleLazio/ParlamentoElettronicoM5S#122]
Discutete qui della classe CSS del bottone, e del relativo codice javascript.

Alla fine deve uscire un componente unico e customizzabile, utilizzabile da LUA senza doversi preoccupare delle meccaniche interne.

![schermata 2013-05-27 alle 13 41 25](https://f.cloud.github.com/assets/3833084/567854/dff68328-c6c3-11e2-9053-bdb76196bf3c.png)

**Comment by ralzakark** [comment]
Per il fit automatico dei testi all'interno del tag anchor è necessario trovare un'alternativa allo script jquery.fittext.js.
Servirebbe uno script che funzioni automaticamente (senza cioè specificare ratio di compressione, min e max fontsize) semplicemente aggiungendo una classe all'elemento heading.
Fatto questo si può passare a creare una funzione in env/ui/ che generi automaticamente il pulsante.

**Comment by gogolander** [comment]
@panseo questa è ancora un'issue aperta o si può considerare risolta?

**Comment by panseo** [comment]
E' risolta
