### ISSUE TITLE
Valutazioni sul fork

### ISSUE THREAD

**Issue by bhack** [Movimento5StelleLazio/ParlamentoElettronicoM5S#16]
Lascio questo interessante link, anche se un po datato, su alcune riflessioni da tenere in considerazione mentre si mantiene un fork. Magari poi qualcuno puo chiudere il ticket e spostarlo nel wiki dei progetti se è piu utile collocarlo li.

http://mako.cc/writing/to_fork_or_not_to_fork.html

**Comment by pierangelo** [comment]
:+1:
