### ISSUE TITLE
TASK AC002 - Scaling 2D della barra delle fasi

### ISSUE THREAD

**Issue by ralzakark** [Movimento5StelleLazio/ParlamentoElettronicoM5S#165]
Creazione di uno script per scalare (attraverso l'attributo "transform: scale" di CSS3) la phasesbar nelle due view: area/show_ext_bs e issue/show_ext_bs. La phasesbar deve occupare tutto lo spazio disponibile tra la info_box (riquadro nero) ed il bordo della box issue.
L'altezza della barra e tutto il contenuto (icone e relative posizione delle stesse) deve scalare proporzionalmente.

**Comment by ralzakark** [comment]
Ho provato questa cosa qui e sembra che funziona... ora però bisogna posizionarla correttamente :/

``` javascript
(function( $ ){

  $.fn.scalebar = function( ) {

    return this.each(function(){

      var $this = $(this);

      var resizer = function () {
        var parent_width = $this.closest('.span9').width()

        // Calculate the resize ratio based on parent div
        var ratio=parent_width/phases_bar_width

        ratioX = ratio;
        ratioY = ratio;

        $this.css('transform', 'scale('+ratioX +', '+ratioY+')');
        $this.css('-webkit-transform', 'scale('+ratioX +', '+ratioY+')');
        $this.css('-ms-transform', 'scale('+ratioX +', '+ratioY+')');
      };

      resizer();

      $(window).on('resize.scalebar orientationchange.scalebar', resizer);

    });

  };

})( jQuery );
```

**Comment by ralzakark** [comment]
Risolto: https://github.com/Movimento5StelleLazio/ParlamentoElettronicoM5S/blob/test/static/js/jquery.scalebar.js

Il posizionamento delle icone va effettuato tramite svg invece che via margin.
Il calcolo della posizione a seconda della fase va integrato nel javascript di controllo.

**Comment by EmanueleSabetta** [comment]
Il plugin jquery-svg lo avete provato?
http://keith-wood.name/svg.html
