### ISSUE TITLE
TASK AC003 - Salvataggio delle keywork di ricerca issue

### ISSUE THREAD

**Issue by ralzakark** [Movimento5StelleLazio/ParlamentoElettronicoM5S#166]
Effettuare uno studio su come memorizzare le parole chiave per la questione e su come effettuare una ricerca in base a queste ultime. Una possibile via è l'utilizzo del tipo di dato postgres "tsvector": http://www.postgresql.org/docs/8.3/static/datatype-textsearch.html. La metodologia per la memorizzazione e per la ricerca va poi implementata nelle rispettive pagine issue: di creazione (wizard/fase 4) e di visualizzazione (issue/show*).

**Comment by EmanueleSabetta** [comment]
L'esempio migliore e' l'uso che fa Instagram di Postgre per gestire i tag:
http://instagram-engineering.tumblr.com/post/40781627982/handling-growth-with-postgres-5-tips-from-instagram

**Comment by ralzakark** [comment]
L'ho implementata con due tabelle: keyword e issue_keyword (associazione).
