### ISSUE TITLE
Design 3 UI Start Page ed Home Page

### ISSUE THREAD

**Issue by ralzakark** [Movimento5StelleLazio/ParlamentoElettronicoM5S#17]
Nel riquadro giallo, sotto la scritta BENVENUTO Nome Cognome appare:

Nome Cognome, il tuo ultimo collegamento è stato il 99/99/9999 alle ore 12:12:99 da **Roma, Lazio**

**Domanda:** E' possibile determinare la posizione da dove l'utente si è collegato?

**Comment by EmanueleSabetta** [comment]
Si, e' una funzione di html5: 
http://dev.w3.org/geo/api/spec-source.html

Qui trovi un demo con sorgenti:
http://html5demos.com/geo

**Comment by EmanueleSabetta** [comment]
Se ti servono i dettagli della Api google per ottenere il nome della citta' a partire dalle coordinate:
https://developers.google.com/maps/documentation/javascript/geocoding#ReverseGeocoding

**Comment by pierangelo** [comment]
conviene comunque verificare che il browser lo supporti.
