### ISSUE TITLE
Design 10 UI [Wizard Step 1 to Step 12] - Barra di Avanzamento

### ISSUE THREAD

**Issue by pierangelo** [Movimento5StelleLazio/ParlamentoElettronicoM5S#186]
che ne pensate di far visualizzare il passo rispetto al persorso intero?

**Comment by EmanueleSabetta** [comment]
Una barra degli step sarebbe eccellente, se riesci a farla. Mi ero posto il problema, ma ovviamente il problema è la grandezza dei caratteri per renderle comprensibili (non basterebbe usare solo il numero, non è sufficientemente espressivo per il nostro target).

Qui ci sono alcuni esempi di barre:
http://www.smashingmagazine.com/2010/01/15/progress-trackers-in-web-design-examples-and-best-design-practices/

**Comment by pierangelo** [comment]
e si, dobbiam valutare un po' di cose.....intanto potrei sostituire il testo  "FASE 1" con  "FASE 1 di 12" 
"FASE 2 di 12" ...

**Comment by EmanueleSabetta** [comment]
Questa è una barra sufficientemente esplicativa, con testo che spiega ogni step:

![misc_step_wizard](https://f.cloud.github.com/assets/3833084/726131/2f5fde26-e0d4-11e2-8ff8-df9735edb9a8.png)

ma già qui con soli 5 step la grandezza dei caratteri è sotto i nostri standard minimi, che sono molto grandi per consentire la lettura agli anziani.

Figuriamoci la nostra che ne ha 11 di step. Saremmo costretti a eliminare persino la parola "step", lasciare solo i numeri. Una cosa del genere:

![searchinsidevideo_pr](https://f.cloud.github.com/assets/3833084/726132/36eafe96-e0d4-11e2-9ab3-621ac2083b0e.png)

Non so quanto sarebbe espressiva, ma tentare non nuoce.
