### ISSUE TITLE
Modifica al design della sezione filtri

### ISSUE THREAD

**Issue by EmanueleSabetta** [Movimento5StelleLazio/ParlamentoElettronicoM5S#187]
Per i filtri invece è troppo caotico lasciarli così. 

Ho deciso di standardizzare le barre sia dei bottoni di ORDINAMENTO che quelli dei FILTRI. Li rifacciamo con gli angoli quadrati e tutti attaccati, come li aveva fatti Panella, con la differenza che agli estremi DX e SX il primo e l'ultimo bottone hanno rispettivamente gli spigoli DX e SX curvi come i bottoni.
In questo modo mantengono la loro identità visiva di bottoni, in quanto gli spigoli sono curvi, ma sono più stretti e compatti, più ordinati, e c'è più spazio per il testo.

Cambiamenti nel design del bottone filtri: 
- sul bottone per "aprire/chiudere", invece di "ELIMINA FILTRI" scriviamo "CHIUDI FILTRI" seguito da un icona svg con due frecce verso il centro che simboleggiano la chiusura
- quando si preme il bottone CHIUDI FILTRI i filtri non si resettano, ma vengono salvati in un cookie della pagina e restano in memoria come settaggio preferenze permanente
- per eliminare i filtri si userà quindi il bottone "QUALSIASI FASE" per la prima categoria, e "TUTTE LE UNITA'" per la seconda.

Cambiamenti nel design dei bottoni della sezione filtri:
- I bottoni filtri saranno con spigoli QUADRATI internamente e spigoli CURVI agli estremi DX e SX di OGNI riga (incluso quando vanno a capo). Vedi immagini allegate.

![barre bottoni curve esempio](https://f.cloud.github.com/assets/3833084/726125/7de985e8-e0d3-11e2-913b-68ef67834d52.png)

![barre bottoni curve nel caso di width stretta esempio](https://f.cloud.github.com/assets/3833084/726124/7dd9d90e-e0d3-11e2-9ae3-930cb323b5a1.png)

**Comment by panseo** [comment]
Bisogna cambiare delle clessi sul codice, ed ho aggiunto in fondo al m5s.css i btn-small-dx btn-small-sx e buton-small-extras

http://www.nono5stelle.it/lf/filtri.html

**Comment by EmanueleSabetta** [comment]
Primo bug report: Ottimo, ora sono ok. Unici bug i seguenti:

![bug report del 2013-06-30 alle 18 13 35](https://f.cloud.github.com/assets/3833084/727535/2c63dc86-e1a1-11e2-96dd-4af587537f2a.png)

**Comment by panseo** [comment]
Il bottone in stato premuto:  l' altezza del bottone inattivo è determinata dallo spessore che crea l' effetto 3D, che sul pilsante premuto non c'è, quindi non credo sia possibile cosi al volo........
In realta il pulsante premuto e alto come i pulsanti inattivi.

**Comment by EmanueleSabetta** [comment]
Ok. Infatti la cosa corretta da fare quando lo si preme sarebbe spostare il pulsante verso il basso di alcuni pixel.

**Comment by ralzakark** [comment]
Scusate, leggo solo ora...
In boostrap esiste il button grouphttp://twitter.github.io/bootstrap/components.html#buttonGroups che fa già questa cosa (bordi tondi ai margini del gruppo).
Inoltre i bottoni non li possiamo staticizzare così, devono essere messi in riga automaticamente in base alla lunghezza delle lettere che ne compongono il testo (ricordo che deve essere multilungua). 
Altro piccolo commento: le fasi dei bottoni non sono messe in ordine e la cosa potrebbe generare confusione.

Una possibile soluzione potrebbe essere quella di inserire nello script lua https://github.com/Movimento5StelleLazio/ParlamentoElettronicoM5S/blob/test/app/main/issue/_filters_btn_bs.lua#L114 che li genera un "conta lettere" che quando raggiunge un numero predeterminato di lettere genera un nuovo button group.

**Comment by panseo** [comment]
Hai ragione bootstrap lo fa, in questo modo dovrebbe scalare anche il margine tondo insieme al bottone....................no non scala,  quindi o li mettiamo,in due righe, oppure si  fà come dice ale, uno script contaparole,
