### ISSUE TITLE
TASK AC012 - Problema bottoni

### ISSUE THREAD

**Issue by ralzakark** [Movimento5StelleLazio/ParlamentoElettronicoM5S#200]
Sembra che se si perde il focus sul bottone durante il click il link non viene caricato.
Si potrebbe provare ad intercettare l'evento click sull'elemento con jQuery così:

``` javascript
$('button').click(function(event){
    // ??
})
```

**Comment by ralzakark** [comment]
Ho testato questa funzione:

``` javascript
$('.btn').click(function(event){
    alert("test");
})
```

Quando si perde il focus il click non viene proprio intercettato...

**Comment by pierangelo** [comment]
ho potuto constatare che i click vengono tralasciati quando stai cliccando nei pressi del bordo dei div che contengono l'heading ( quelli denominati fittext)

![schermata del 2013-07-02 19 54 22](https://f.cloud.github.com/assets/497527/738166/93227b4e-e340-11e2-83e8-1cdf4daa020f.png)

se rimuovo quel div i click vengono sempre intercettati

**Comment by ralzakark** [comment]
Ho fatto un test con un semplice div ed il problema si presenta comunque. Sembra che il click non va nei pressi della zona di leading del testo.

**Comment by ralzakark** [comment]
Risolto: https://github.com/Movimento5StelleLazio/ParlamentoElettronicoM5S/blob/test/static/js/jquery.intercept_mousedown.js
