### ISSUE TITLE
Design 3 UI  [Task C2] - Una volta scelta l'assemblea a cui si vuole partecipare nella Start Page, premendo il bottone viene servita la pagina dell'utente, con visualizzate 4 OPZIONI

### ISSUE THREAD

**Issue by pierangelo** [Movimento5StelleLazio/ParlamentoElettronicoM5S#22]
[Task C2]
- Una volta scelta l'assemblea a cui si vuole partecipare nella Start Page, premendo il bottone viene servita la pagina dell'utente, con visualizzate 4 OPZIONI......

wiki:
https://github.com/Movimento5StelleLazio/ParlamentoElettronicoM5S/wiki/Design-3-UI-Start-Page-ed-Home-Page

**Comment by EmanueleSabetta** [comment]
A che punto siamo? Ci sono problemi nel realizzarle senza jQuery?
Domani posto sulla wiki il design delle 4 pagine a cui portano i 4 bottoni, cercando sempre di modificare il minimo indispensabile.

**Comment by pierangelo** [comment]
E' stata committata. Alessandro ha provato a fare il merge sul brach test del repo ma ha avuto problemi. Invece il merge con il suo repo e' andato a buon fine.

**Comment by pierangelo** [comment]
l'ha provata in locale ed ha postato questo comportamento con Chrome

![11492_10200276117198360_1853828795_n](https://f.cloud.github.com/assets/497527/353311/c6a79e8c-a07d-11e2-88cd-c140ae2921d5.jpg)
