### ISSUE TITLE
BUG DA FIXARE - Wizard - Aree di Competenza

### ISSUE THREAD

**Issue by EmanueleSabetta** [Movimento5StelleLazio/ParlamentoElettronicoM5S#228]
✓ - il primo bottone non è allineato con il testo
✓ - il bottone della prima riga deve esserci, ma dovrebbe essere desaturato, come disattivato o fissato, per far capire che non è modificabile
✓ - il testo della label "area di competenza" del primo ha la dimensione giusta dei font, mentre dovremmo portare le altre 3 label alla stessa dimensione, restringendo il controllo dropdown list orizzontalmente
✓ - i bottoni dovrebbero avere più distanza dal bordo sinistro
✓ - il testo "informazioni sulle aree di competenza..etc." in piccolo sotto i dropdown list li toglierei, tanto sono inutili e comunque troppo piccoli per essere leggibili

![wizardareecompetenza](https://f.cloud.github.com/assets/3833084/794396/6e3c7ac2-ec97-11e2-98b3-13d5132d2282.jpg)

**Comment by ralzakark** [comment]
1) E' necessario creare le strutture dati. La pagina deve prendere dati dinamicamente dal database.
2) Il design potrebbe essere rivisto: il pulsante, testo e select sono sulla stessa riga e la cosa non si adatta bene con viewport a basse width.
3) Si potrebbe fare anche in tutt'altra maniera... presentiamo una lista di TUTTE le aree tecniche e poi l'utente può selezionarne massimo 4 (oltre la quarta selezione ad es. ti potrebbe apparire un popup che ti dice di selezionare prima qualcosa)

**Comment by EmanueleSabetta** [comment]
- le modifiche alla struttura dati stanno arrivando insieme alla pagina 13. Ci sono molte nuove cose per le commissioni.
- se si perde l'allineamento orizzontale è necessario legare graficamente i 3 componenti in un altro modo, ad esempio con un box. 
- la lista esplicitata è molto lunga, almeno 1000 entry, e renderebbe difficile trovare i bottoni BACK e NEXT che sarebbero spinti in fondo ad una lunghissima pagina. Dovrebbe essere quindi inserito sempre come box a scorrimento. Questi di solito sono di difficile uso quando bisogna selezionare più elementi in stile checkbox, in quanto fissando un max di 4 elementi ad esempio, arrivati al 4° se l'utente vuole selezionarne uno diverso deve prima deselezionarne uno precedentemente selezionato tornando indietro nella lunga lista, per poi ripetere il processo via via che la scorre tutta. 

Ora penso ad una soluzione ibrida tra l'incolonnamento dei field e la checkbox a scorrimento.

**Comment by ralzakark** [comment]
Anche una select con 1000 entry non è molto user friendly...ogni volta devo aprire la lista e scorrerla tutta nuovamente cercando di capire a che punto ero arrivato a leggere le entry.
In entrambi i casi comunque, le entry dovrebbero essere ridotte o filtrate in qualche maniera.

**Comment by gogolander** [comment]
Cambiato layout e sostituito con tag
