### ISSUE TITLE
TASK AC016 - Creazione di una view footer per i social plugins

### ISSUE THREAD

**Issue by ralzakark** [Movimento5StelleLazio/ParlamentoElettronicoM5S#246]
Creazione di una view footer per i social plugins come da immagine:
![GitHub Logo](http://i40.tinypic.com/2daypt2.png)
La footer view sarà poi utilizzata nelle varie viste dettagli dove è possibile la condivisione via social plugins.

**Comment by panseo** [comment]
fixato
