### ISSUE TITLE
Problema font Optima

### ISSUE THREAD

**Issue by ralzakark** [Movimento5StelleLazio/ParlamentoElettronicoM5S#250]
Non è preinstallato su windows 8 http://en.wikipedia.org/wiki/List_of_Microsoft_Windows_fonts

Si potrebbe usare in fallback L'Open Sans: http://www.google.com/fonts/specimen/Open+Sans disponibile via Google Font API

**Comment by EmanueleSabetta** [comment]
Optima è imbattibile ma è a pagamento:
http://www.fonts.com/font/linotype/optima/roman/web-font

Ma ce ne sono molti gratuiti che gli si avvicinano, tipo Belleza: 
http://www.fontsc.com/font/belleza

o Gilda Display
http://www.fontsc.com/font/gilda-display

**Comment by ralzakark** [comment]
Per la cronaca, c'è un bug aperto da 11 mesi su Chrome/Windows: https://code.google.com/p/chromium/issues/detail?id=137692 .. niente anti-aliasing sui font :/

Ecco come si vede Belleza:

![Belleza](http://i42.tinypic.com/2lkfok9.png)

..una schifeza, sembra un sito che vende katane :)

**Comment by EmanueleSabetta** [comment]
Trovato il font che fa al caso nostro: si chiama OREGON LDO. E' freeware ed è molto simile all'Optima. Ora lo sostituisco in tutti gli SVG. Bisogna naturalmente caricarlo insieme alla pagina.

http://www.fontspace.com/luke-owens/oregon-ldo

**Comment by EmanueleSabetta** [comment]
Bisogna generare il WebFont per il font OREGON LDO a partire dal file .ttf, usando il generatore del sito Fontsquirrel.com:

http://www.fontsquirrel.com/tools/webfont-generator

Qui la guida su come usarlo: 
http://www.creativebeacon.com/a-guide-to-using-font-face-in-your-websites/

Ecco il risultato, usate questo in tutte le pagine HTML:
File zip del WebFont OREGON LDO:
http://goo.gl/a281wa
