### ISSUE TITLE
Bug: Visualizzazione della "procedura di Registrazione"  

### ISSUE THREAD

**Issue by pierangelo** [Movimento5StelleLazio/ParlamentoElettronicoM5S#253]
La visualizzaizone del box "Guida all'iscrizione" e' presente anche agli utenti loggati nel sistema
![schermata del 2013-07-26 19 32 18](https://f.cloud.github.com/assets/497527/864099/8a0f77fa-f619-11e2-858c-afd0b8214b93.png)

**Comment by ralzakark** [comment]
Da design deve essere presente

**Comment by pierangelo** [comment]
il design e' sbagliato :)

2013/7/27 Puccio notifications@github.com

**Comment by EmanueleSabetta** [comment]
E' una opzione che ho lasciato anche dopo il login per consentire di accedere alle indicazioni su dove e come registrarsi anche dopo che ci si è registrati, in caso fossero necessarie per informare un amico dell'utente interessata ad iscriversi. Poiché le procedure possono cambiare è importante che l'utente registrato abbia sempre un modo evidente e intuitivo per leggere queste informazioni ed inviarle ad un altro utente espandendo la base utenti per passaparola. Nel caso specifico premendo quel bottone si aprirebbe la pagina della guida con le info aggiornate, e potrebbe condividere la url con un amico (probabilmente metteremo un bottone "Invita un tuo amico a Partecipare al Parlamento Elettronico Online inviandogli il link a questa pagina via email".
