### ISSUE TITLE
Togliere loghi

### ISSUE THREAD

**Issue by gogolander** [Movimento5StelleLazio/ParlamentoElettronicoM5S#266]
L'interfaccia è piena di loghi del m5s da togliere.

**Comment by pierangelo** [comment]
ok prima issue va quasi bene, ma devi cercare di essere molto specifico: devi indicare tutte le pagine coinvolte.
ad esempio la issue andrebbe editata cosi:

loghi del m5s da togliere nelle pagine:
1.
2.
3.
....
....

**Comment by gogolander** [comment]
_registration_info.lua: mi pare sia solo quella.

**Comment by pierangelo** [comment]
intendevo le pagine html....

quando fai una segnalazione devi cercare di evitare parole del tipo "mi pare...."

**Comment by gogolander** [comment]
asp, my man, che non ho capito bene a quale pagina html ti riferisci. non c'è una pagina html, c'è solo lo script lua che poi viene tradotto. Non ti posso dire quale sia la pagina html perché non so esiste.
comunque questo trunk viene visualizzato in index/index.html
