### ISSUE TITLE
Barra assemblee

### ISSUE THREAD

**Issue by gogolander** [Movimento5StelleLazio/ParlamentoElettronicoM5S#269]
Introdurre un pulsante "Indietro" per tornare alla home dopo essere entrati in una assemblea.

**Comment by gogolander** [comment]
@panseo questa la dobbiamo fare assieme per forza...

**Comment by panseo** [comment]
yes @gogolander

**Comment by gogolander** [comment]
wonderful. plz sync: wizard fixed :)
