### ISSUE TITLE
Registrazione dati connessione utente

### ISSUE THREAD

**Issue by ralzakark** [Movimento5StelleLazio/ParlamentoElettronicoM5S#27]
Un po' di idee per la registrazione dei dati utente:
## Requisiti:
- Registrazione dei dati degli ultimi N (configurabile) accessi dell'utente (Indirizzo IP, Posizione, Data/ora Login)
- Avvertire l'utente in caso di due distinti login con orari ravvicinati e posizioni incompatibili
- Possibilità per l'utente di salvare (via cookie + record nel db) il browser utilizzato con una label e contestualmente inviare all'utente una email di notifica (come avviene in Facebook)
- Possibilità per l'utente di cancellare in qualsiasi momento i dati di connessione.
- Possibilità per l'utente di cancellare in qualsiasi momento i browser abilitati
## Creazione di una tabella "member_connection"
- Campo "member_id" -> integer
- Campo "ip_address" -> integer
- Campo "position" -> point [oppure 2 colonne con decimal(10,6) ]
- Campo "login_time" -> timestamp with time zone
## Creazione di una tabella "member_browser"
- Campo "member_id" -> integer
- Campo "cookie" -> text
- Campo "label" -> text

**Comment by EmanueleSabetta** [comment]
Ottime idee. Sull'abilitazione dei browser però non saprei, è troppo facile da ingannare. Inoltre impedirebbe l'accesso da terminali non previsti dallo stesso utente. Però segnalare al login il browser con cui si è connesso l'ultima volta può aiutare l'utente a rilevare una intrusione a sua insaputa, esattamente come posizione e orario.

**Comment by ralzakark** [comment]
Implementata registrazione coordinate.
Vedi Design 1, Task A8: https://github.com/Movimento5StelleLazio/ParlamentoElettronicoM5S/wiki/Design-1---Strutture-Dati
