### ISSUE TITLE
Testi dei messaggi

### ISSUE THREAD

**Issue by gogolander** [Movimento5StelleLazio/ParlamentoElettronicoM5S#272]
Alcuni testi iniziano tutti con la prima lettera maiuscola, inoltre a volte non traduce il termine "welcome"
- barra welcome delle assemblee

**Comment by mwithi** [comment]
Ciao Vincenzo, intendi dire che alcuni testi hanno la prima lettera di ogni parola maiuscola? Dove lo non viene tradotto "welcome"?

**Comment by gogolander** [comment]
non tutte le parole di tutti i messaggi ma una parte considerevole sì. "welcome", come puoi immaginare, non me lo traduce con sistematicità nella homepage.

**Comment by mwithi** [comment]
Intendevo dire se ti riferisci a casi come questo "Administrator, Ti Trovi Nell'Assemblea Della Regione Lazio" o ad altro.

Per il "welcome" lo vedo tradotto sempre, per caso hai degli steps per riprodurre l'errore?

**Comment by gogolander** [comment]
Sì mi riferisco proprio a quei casi che segnali. No, non riesco a riprodurlo: ed è un po' frustrante. Forse è solo un colpo di testa del mio pc, non so. Fatto sta che sul mio pc non lo traduce ma sul server di test sì.

**Comment by mwithi** [comment]
Allora nel primo caso io il testo lo vedo così proprio nel file delle traduzioni... non ho capito ancora però perché modificarlo non sortisce alcun effetto.

La chiave welcome dovrebbe essere ugualmente tradotta in locale/translation.it, tra l'altro vedo solo tre chiavi:
["Homepage welcome text"]="TI TROVI NELL'ASSEMBLEA [...]
["Homepage welcome text2"]="QUI SI DISCUTONO LEGGI E [...]
["Homepage welcome"]="BENVENUTO";

Se sul tuo PC non lo traduce mai, mentre sul server lo traduce sempre allora è diverso...

**Comment by gogolander** [comment]
hai deployato le modifiche dopo averle fatte?
effettivamente è molto diverso, infatti non penso di toccare niente: sarà un problema locale di qualche tipo che non riesco a trovare.

**Comment by mwithi** [comment]
[mode_english]

How to deploy the changes to locale/translation.it? I've modified the file directly in /opt/ParlamentoElettronicoM5S and restarted lighttpd, not enough?

**Comment by panseo** [comment]
Hi, about this topic, I am finishing the new interface with new texts for buttons, this weekend I will do a git pull on with these changes

**Comment by mwithi** [comment]
panseo, do you mean new interface with new translation file?

**Comment by gogolander** [comment]
no: to deploy and actually apply your edit run the script extras/install.sh: available options are "auto" to recompile parelon as a whole or "-f" to simply copy your mods in the running dir.

**Comment by panseo** [comment]
in my local Virtual machine, you can see a example in attachment
![homepage-bs](https://cloud.githubusercontent.com/assets/4426646/3348450/a2280e66-f92d-11e3-84c4-16c292e49296.jpg)

**Comment by gogolander** [comment]
in a (not so) future release I think is for the best to merge "proposte" "tuo gruppo" and "altri gruppi" buttons, making them just filtering the all proposals. for now let's just stay with them.

**Comment by mwithi** [comment]
@gogolander tried -a and -f, changes actually copied in the dest folder, but not changes in the browser, even by clearing the browser cache... any suggestion?

@panseo @gogolander I think discussion about the layout can start a different issue, or a thread in facebook, what do you think?

**Comment by gogolander** [comment]
I think it is just too soon to get into that discussion.
try not with "-a" but with "auto", "-" before it.

**Comment by mwithi** [comment]
Tried "auto", cleared browser cache, restarted lighttpd, no changes... mumble mumble...

**Comment by gogolander** [comment]
open an issue and attach logs and splashscreen, plz...

**Comment by mwithi** [comment]
no, sorry, my mistake, there where several translations of that... solved by changing the right one :+1: 

So the issue is due to the translation file, there's no text processing between translations files and the view.

@panseo is there anybody in charge for translations?

**Comment by mwithi** [comment]
Created a pull request for this issue, I've not found other cases but I'm not sure. In case more translations changes are needed, I suggest to open another issue as "missing" or "translations", not "bug"

**Comment by gogolander** [comment]
Please leave this kind of bugs to @panseo. You would be useful contributing to issues as #230.

**Comment by mwithi** [comment]
ok, but I was just starting with something very simple to understand the flow... 

for instance: I was in the "wrong branch", should I fork "test" branch and pull over there?

**Comment by gogolander** [comment]
you can't fork a branch: you fork a repository, that has all the branches within it. you have to switch to a branch, with the command "git checkout branchname".
Yes, you have to pull from yourRepo:test -> upstream:test

**Comment by mwithi** [comment]
Ok, I tried again, check please if I did it right this time. Thanks
