### ISSUE TITLE
proposta senza titolo

### ISSUE THREAD

**Issue by ilbarillo2014** [Movimento5StelleLazio/ParlamentoElettronicoM5S#318]
inserendo una proposta (eletto, VII commissione, "Crea nuova questione"), nei dettagli della proposta non appare il titolo.
esempio
Q12 - No title for this issue!

**Comment by gogolander** [comment]
questo credo sia dovuto in qualche modo alla vecchia interfaccia di liquid

**Comment by gogolander** [comment]
E' dovuto al fatto che i campi del wizard e quelli del liquid sono diversi.

**Comment by gogolander** [comment]
In futuro non si ripresenterà.
