### ISSUE TITLE
passaggio a fase discussione

### ISSUE THREAD

**Issue by ilbarillo2014** [Movimento5StelleLazio/ParlamentoElettronicoM5S#319]
attualmente nell'area VII commissione ci sono
Questioni: 12 nuove · 0 in discussione · 0 congelate · 0 in votazione · 0 concluse · 0 cancellate

non e' stato effettuato il passaggio alla fase successiva, nonostante siano scaduti sia i tempi di discussione e votazione.
l'ipotesi e' che non ci siano stati sufficienti supporters a superare il quorum ed entrare in fase di discussione...ma in questo caso non e' chiaro lo status della proposta e i tempi per considerarla decaduta (soprattutto nel caso di questioni urgenti)

grazie

**Comment by gogolander** [comment]
controllare le query al database: le informazioni sono salvate ma non processate.

**Comment by gogolander** [comment]
trigger, view e stored procedures mancanti nel database

**Comment by gogolander** [comment]
servizi di aggiornamento non attivi: liquid_feedback_core verrà reinstallato per evitare ulteriori problemi.

**Comment by gogolander** [comment]
solved.
