### ISSUE TITLE
Utilizzo di JQuery

### ISSUE THREAD

**Issue by EmanueleSabetta** [Movimento5StelleLazio/ParlamentoElettronicoM5S#32]
Stavo pensando che jQuery appesantisce di molto un sito web e può creare problemi di scalabilità e verifica del codice. Se possiamo dobbiamo evitare di usarlo, limitandoci a mantenere il codice più semplice e pulito possibile, o provare qualche alternativa più snella (tipo jQ.Moby). Alcune funzioni HTML5 per la geolocalization potrebbero essere fornite da piccole librerie come questa:
https://github.com/estebanav/javascript-mobile-desktop-geolocation/

Per cosa pensate che possa essere necessario JQuery?

**Comment by pierangelo** [comment]
il vantaggi:
1. il piu' evidente e' il compatibilità cross-browser.
2. Web 2.0 ready, ovvero per noi sarebbe tutto pronto qualora volessimo fare qualcosa di piu' moderno :)

per  me  :+1:

**Comment by ralzakark** [comment]
quoto pierangelo e aggiungo delle considerazioni:
1. Data l'alta distribuzione, la libreria è sicuramente più stabile e performante di qualsiasi soluzione ad-hoc che possiamo implementare (almeno per ora)
2. Possiamo rimuovere le funzioni inutilizzate per migliorare le performance
3. Possiamo invocare la libreria solo ove necessario
4. Non uso la libreria per la geolocalizzazione ma solo per le richieste asincrone (AJAX)

**Comment by EmanueleSabetta** [comment]
Aspetti negativi:
- Non potendo dipendere da terze parti, non potremo usare il caching google di jQuery. Il che significa un grosso impatto sul server.
- Inoltre sempre per la scalabilità l'uso di AJAX va ridotto al minimo a prescindere, se non eliminato del tutto.
- JQuery è lento perché scritto per essere compatibile all'indietro con moltissime versioni e piattaforme. Lo stesso codice di una operazione riscritto specificatamente per HTML5 e CSS3 (che possiamo definire dei requisiti per usare il portale) si dimostra molte volte più veloce (si veda questo benchmark JQuery vs JQMobi
  http://www.codefessions.com/2012/08/performance-of-jquery-compatible-mobile.html )

**Comment by ralzakark** [comment]
1. Non ho capito bene. Non dipendere da terze parti è un requisito? Per la geolocalizzazione comunque dovremmo farlo.
2. Vero. In ogni caso l'ajax (vs il server liquid) è utilizzato per ora solo al login. E' un singolo RPC per postare le coordinate ad una action che stora su db (quindi necessaria, se non vogliamo farlo in due fasi con una GET). Nel task C3 si potrebbe usare l'AJAX al posto dell' ui.paginate (che precarica tutto, pierangelo correggimi se sbaglio..) ma non ne vedo la necessità immediata dato che le issue con un determinato filtro non dovrebbero cambiare di continuo. Bisogna sicuramente programmare bene la cosa in anticipo. Lazy data con un alto numero di RPC migliorano la navigazione per l'utente ma possono rallentare parecchio. Rimando poi a questo link sul caching di jQuery: http://encosia.com/3-reasons-why-you-should-let-google-host-jquery-for-you/
3. Le mie considerazioni erano riguardo JQuery vs Fai-da-te. Nessuna obiezione ad usare altre librerie a patto che siano ben testate. Ho dato un'occhiata a JQMobi (che per altro sono parte dell' App Framework di Intel, se non ho capito male) e credo che posso sostituirle a JQuery senza cambiare il codice.

**Comment by EmanueleSabetta** [comment]
Per la geolocalizzazione non dovremo appoggiarci a server terzi, perché è il browser dell'utente che fornisce le coordinate. Solo per la ricerca del nome città corrispondente serve consultare un server terzo, ma questo lo si fa client-side ad ogni visualizzazione, il dato memorizzato è solo la coordinata geografica fornita dal browser.
Come il browser ottiene i dati di localizzazione non è importante, HTML5 prevede solo che li fornisca senza specificare il metodo.

Lazy data = morte della scalabilità. Manteniamo le cose semplici ed essenziali, è il segreto della scalabilità di Liquid.

**Comment by pierangelo** [comment]
Concedetemi di dare un'occhiata a jQMobi.
