### ISSUE TITLE
proposta non ritirata

### ISSUE THREAD

**Issue by ilbarillo2014** [Movimento5StelleLazio/ParlamentoElettronicoM5S#320]
i11: ODG ATTIVAZIONE URGENTE DELLO SCREENING NEONATALE SU TUTTO IL TERRITORIO REGIONALE

e' stata ritirata ma risulta ancora disponibile, e non rientra fra quelle ritirate, e' ancora in stato discussione

Questioni: 12 nuove · 0 in discussione · 0 congelate · 0 in votazione · 0 concluse · 0 cancellate

**Comment by gogolander** [comment]
per qualche motivo, lua continua a mostrarla anche se è stata ritirata...

**Comment by gogolander** [comment]
Conseguenza del bug #319
