### ISSUE TITLE
modifica testo

### ISSUE THREAD

**Issue by ilbarillo2014** [Movimento5StelleLazio/ParlamentoElettronicoM5S#322]
https://test.parelon.com/lf/issue/show_ext_bs/13.html?view=area&orderby=creation_date&interest=any&scope=all_units&ftl_btns=false&state=admission&desc=false

<Data limite per raggiungere il quorum di sostenitori: -00:04:36 rimanenti>

da sostituire con:
"tempo trascorso per raggiungere il quorum di sostenitori" e poi toglierei il valore negativo

<Soluzioni proposte:
Vi sono attualmente 1 proposte per risolvere la questione sollevata. Decidi a quale dare il tuo sostegno o presenta una proposta tua. Almeno una proposta tra quelle presentate deve raggiungere il quorum di sostenitori entro -00:04:36 affinche' la questione venga ammessa alla fase successiva.>

da sostituire con:
<Soluzioni proposte:
Vi sono attualmente 1 proposte per risolvere la questione sollevata. Decidi a quale dare il tuo sostegno o presenta una proposta tua. Almeno una proposta tra quelle presentate deve raggiungere il quorum di sostenitori, ed e' trascorso un tempo di -00:04:36 affinche' la questione venga ammessa alla fase successiva.>

**Comment by gogolander** [comment]
Probabilmente collegato al #319
