### ISSUE TITLE
mancato aggiornamento stato della proposta superato il numero minimo di sostenitori

### ISSUE THREAD

**Issue by ilbarillo2014** [Movimento5StelleLazio/ParlamentoElettronicoM5S#323]
la proposta inserita rimane in stato "ammissione" e nonostante gli utenti sostengano la proposta (quindi superato il quorum di ammissione alla discussione), la proposta rimane in attesa sostenitori...

0 Sostenitori
(0 Potenziali sostenitori)

**Comment by ilbarillo2014** [comment]
nessuna proposta registra ancora un numero di sostenitori diverso da zero...nonostante gli utenti stiano sostenendo la proposta (vedi p15)

**Comment by gogolander** [comment]
Conseguenza del bug #319
