### ISSUE TITLE
modifica pannello inserimento utenti certificatore

### ISSUE THREAD

**Issue by ilbarillo2014** [Movimento5StelleLazio/ParlamentoElettronicoM5S#325]
1) oltre al numero di carta d'identita' serve la data di scadenza ?
2) e' possibile inserire altri documenti validi alternativi alla carta d'identita', come la patente ?
3) se il domicilio e' uguale alla residenza, come nella maggior parte dei casi, si possono per default copiare automaticamente su domicilio i dati gia' inseriti per la residenza ? questo velocizzerebbe il lavoro del certificatore, soprattutto se c'e' molta coda all'infopoint o un numero alto di utenti da inserire

**Comment by gogolander** [comment]
1) non so: si può sempre indicarla dopo il numero del documento. però non credo: una volta certificata l'identità noi facciamo affidamento solo sul serial del token per continuare la certificazione.
2) sì, basta indicare gli estremi
3) possibile ma non in lua :)
