### ISSUE TITLE
mancata attivazione aree utente

### ISSUE THREAD

**Issue by ilbarillo2014** [Movimento5StelleLazio/ParlamentoElettronicoM5S#326]
quando un utente entra per la prima volta, non vede nulla....e quindi non puo' fare nulla.

non vengono abilitate le aree tematiche alle quali un cittadino puo' interessarsi.
l'amministratore entra sull'utente lf, e abilita "regione lazio" e poi "commissione I", "commissione II", ecc.
in questo modo l'utente vede tutte le aree, puo' leggere le proposte...e iscriversi all'area di interesse.

non e' possibile procedere manualmente per ogni singolo utente che viene attivato... e' necessario abilitare per default l'utente che seleziona l'area di appartenenza "regione lazio" a tutte le commissioni disponibili.

grazie

**Comment by gogolander** [comment]
impossibile riprodurre l'errore: attualmente lavora bene.
