### ISSUE TITLE
invia email con codice attivazione

### ISSUE THREAD

**Issue by ilbarillo2014** [Movimento5StelleLazio/ParlamentoElettronicoM5S#327]
capita molto spesso che gli utenti non ricevono l'invito a partecipare, e sembra che la mail non esista nemmeno sotto spam.

in questo caso il certificatore deve utilizzare la funzione "invia email con codice attivazione".
questa funzione non e' attiva.

si richiede l'attivazione in modo da bypassare l'errore di mancato invio mail
grazie

**Comment by gogolander** [comment]
invio email riparato.
