### ISSUE TITLE
barra verticale quorum con dati incorretti sostenitori

### ISSUE THREAD

**Issue by ilbarillo2014** [Movimento5StelleLazio/ParlamentoElettronicoM5S#332]
in fondo al pannello "Dettagli questione Q15" https://test.parelon.com/lf/issue/show_ext_bs/15.html?state=any&orderby=event&interest=any&scope=all_units&ftl_btns=false&view=homepage&desc=false

risulta che 2 sostenitori hanno correttamente fatto superare il quorum e la barra mostra il 100% in verde
la linea verticale blu pero' riporta un dato erroneo (0 sostenitori)

**Comment by gogolander** [comment]
problema di arrotondamenti
