### ISSUE TITLE
mancanza dati certificazione

### ISSUE THREAD

**Issue by ilbarillo2014** [Movimento5StelleLazio/ParlamentoElettronicoM5S#333]
inserendo un utente e compilando tutti i campi, l'utente viene correttamente inserito in lf (admin-utenti)
ma SENZA il campo "identificazione" (inserisco io a mano il serial del token) e il campo "email di notifica" (inserisco io indirizzo mail).

inolte l'utente e' inserito senza nessuna area attiva...devo mette il flag su regione lazio, e sulle singole commissioni

**Comment by gogolander** [comment]
per quanto riguarda la mail di notifica, la gestisce lui: tranquillo, non devi modificare nietne a mano.
il campo di "identificazione" è stato riparato.
Sul problema dell'ereditarietà delle aree attivate, non posso ancora dire che il problema sia risolto.

**Comment by gogolander** [comment]
il primo punto è stato completamente risolto.

**Comment by gogolander** [comment]
il secondo è invalido.
