### ISSUE TITLE
Mancato accesso a wizard creazione guidata proposte x cittadini

### ISSUE THREAD

**Issue by ilbarillo2014** [Movimento5StelleLazio/ParlamentoElettronicoM5S#336]
Per gli eletti l'accesso all'interfaccia originale LF per l'inserimento di proposte, e' ok (1 sola schermata per inserire direttamente il testo di legge gia' pronto)
Per i cittadini invece e' necessario che sia attiva la procedura guidata per l'inserimento: attualmente cliccando su "Crea nuova questione", per l'area selezionata, si arriva ancora alla vecchia schermata LF.

**Comment by gogolander** [comment]
solo perché sei eletto...
