### ISSUE TITLE
LF 3.0

### ISSUE THREAD

**Issue by ilbarillo2014** [Movimento5StelleLazio/ParlamentoElettronicoM5S#338]
Prima del rilascio della prima release della piattaforma, verifichiamo se siamo all'ultimo livello del core lf.
sembra che sia uscita da poco l'ultima versione: valutiamo i bug corretti e le nuove funzioni, in modo da essere allineati.

**Comment by gogolander** [comment]
l'unico aggiornamento importante apportato è la nuova interfaccia grafica: dal lato "cambiamenti significativi" nulla da segnalare.
