### ISSUE TITLE
TASK F1, F2, F3: Design 6 UI SCELTA AREE

### ISSUE THREAD

**Issue by ralzakark** [Movimento5StelleLazio/ParlamentoElettronicoM5S#41]
### Pagina di Scelta Area Tematica:

Mi sembra di capire che le pagine a livello 3, per scelta delle aree tematiche (area) per la  lettura e votazione delle proposte (initiative) sono 4:
1. Task F1  - Assemblea Pubblica Regione Lazio: Proposte dei CITTADINI
2. Task F2a - Assemblea Pubblica Regione Lazio: Proposte degli ELETTI
3. Task F2b - Assemblea Pubblica Regione Lazio: ALTRI GRUPPI POLITICI
4. Task F3  - Assemblea INTERNA M5S Lazio: Proposte degli ISCRITTI

Per le quattro pagine sarebbe possibile creare una sola view e passare con l'opzione "params" dell'ui di webmcp un valore che permetta alla view di distinguere quali issue mostrare.

Come distinguere le issue ? Possiamo filtrare per autore (cittadini/eletti/politici/iscritti m5s)?

La relazione parentale per le proposte di LQ-FB è fatta più o meno così:

issue (questioni) -> initiative (proposta) -> draft (bozza)

Quando viene creata una issue, vengono anche creati contestualmente una initiative ed un draft. Più draft (sempre dello stesso autore) afferiscono ad una singola initiative. Più initiative (di diversi autori) afferiscono ad una singola issue.

Di questi, solo il draft possiede un author_id, ovvero l'identificativo di chi l'ha creato. Dato che comunque i draft, per una data iniziativa, sono creati tutti da uno stesso autore è quindi possibile risalire all'autore dell'initiative partendo da uno qualsiasi dei draft.

La separazione tra gli autori avviene quindi tra issue ed initiative.

Domande: 
1) Dando per scontato che un cittadino possa sempre, nei limiti delle tempistiche e delle unità abilitate, creare una initiative (proposta) alternativa per una issue (questione) creata da altri cittadini, quest'ultimo, può anche creare proposte alternative per le issue degli eletti e degli altri gruppi politici? Oppure può solo votarle e fare suggerimenti?

2) Come vengono create le issue degli altri gruppi politici? Da chi vengono inserite, dagli eletti?

3) Le issue/initiative create da un eletto o da un altro gruppo politico sono create nelle stesse unità ed aree utilizzate per issue dei cittadini?

4) Stessa domanda per l'assemblea interna m5s lazio. Ci sono unità ed aree completamente diverse o sono sovrapposte?

4) E' forse il caso di inserire un creator_id anche per le issue quindi, in modo da distinguere più facilmente quali di queste mostrare nell'ui ed evitare che possano essere create proposte alternative? Oppure, se a questo livello abbiamo già selezionato una unit (e le unit sono diverse tra cittadini, eletti, etc) usiamo semplicemente la tabella "privilege"?

**Comment by EmanueleSabetta** [comment]
Chiaramente si, basta un solo script LUA per generarle tutte. Basta modularizzare con una funzione che si occupa di generare le liste. Il parametro è dato da chi ha aperto la ISSUE (non da chi propone le iniziative alternative, quelle le possono proporre anche i cittadini o gli eletti, o persino gli stessi gruppi politici). 

Sarà più chiaro quando posterò la wiki della pagina "crea proposta", ma il punto è che servirà certamente modificare la struttura dati per aggiungere l'attributo ALTRI GRUPPI POLITICI delle proposte create dagli eletti, e solo gli utenti con tag eletti possono selezionare questo attributo booleano quando creano una nuova proposta.

Quindi vi saranno le seguenti 4 possibilità di autorship:
ISCRITTI - proposta che ha "autore = utente normale, tag = livello certificazione >= 3" e tag "altri gruppi politici = false"
CITTADINI - proposta che ha "autore = utente normale, tag = livello certificazione >= 1" e tag "altri gruppi politici = false"
ELETTI - proposta che ha "autore = utente eletto" e tag "altri gruppi politici = false"
ALTRI GRUPPI POLITICI - proposta che ha "autore = utente eletto" e tag "altri gruppi politici = true"

Non vi è quindi bisogno di indicare nella Issue nulla a parte l'autore e questo attributo booleano, che potremo chiamare "proposta_di_altri_gruppi_politici".

Invece le iniziative, ovvero la proposta di alternative alla Issue di base, sono apribili da tutti e in tutti i casi, non importa chi sia l'autore.

Le aree e le unità sono completamente distinte tra assemblea interna e cosa pubblica.

**Comment by pierangelo** [comment]
Ale, quali e quanti task hai preso? :)

**Comment by ralzakark** [comment]
F1, F2, F3.

**Comment by pierangelo** [comment]
dopo che avevo preso c1,c2,c3 in una sola volta, avevamo detto non piu' di uno a testa :)

e per quanto riguarda il nome della Issue qui nella wiki?  :)

**Comment by pierangelo** [comment]
:+1:

**Comment by ralzakark** [comment]
Pensavo di fare una sola view per tutte e quattro le pagine. All'interno poi metto la logica per quali aree mostrare.
Devo pensare meglio a come selezionare le unit una volta arrivati al livello 3. Ad esempio, se pensiamo che le unit sono diverse a seconda dell'assemblea (cittadini, eletti, iscritti, o degli altri gruppi parlamentari) a questo livello dovremmo già avere la selezione delle unit da mostrare (selezione effettuata dall'utente a livello 1 e 2) e rimangono da filtrare solo le aree.

La logica per la scelta della unit potrebbe essere questa: 

Consideriamo un albero delle unit fatto così:

Cittadini:
- Latina
- Viterbo
- Municipio I
- Municipio II
- Municipio IX

Eletti:
- Latina
- Viterbo
- Municipio I
- Municipio II
- Municipio IX

Altri Gruppi Politici:
- Latina
- Viterbo
- Municipio I
- Municipio II
- Municipio IX

Iscritti:
- Proposte
- Liquid

Livello 1-2: L'utente sceglie, tramite la start page e la home page, quale gruppo di unit visualizzare. 
Livello 3: L'utente filtra le aree e ne sceglie una
Livello 4: L'utente filtra le proposte per stato
Livello 5: Ordinamento delle proposte

Esempio: Un utente del IX municipio, sceglie di visualizzare le proposte degli eletti e preme sui bottoni corrispondenti nella start page (Assemblea Lazio) e nella home page (Eletti). Questa azione crea un selector per la unit che viene filtrato per gruppo/assemblea a livello 1 e 2 e per le unità dove l'utente è abilitato (Municipio IX in questo caso) a livello 3. Il selector viene eseguito a livello 3 e da questo si ricavano le aree che nello stesso livello vengono ulteriormente filtrate.
Nota: La "homepage" (livello 2) è speciale perché applica una selezione diretta delle issue senza filtrare per gruppo/assemblea.

Quando l'utente poi vota, propone alternative o richiede una commissione, verrà effettuato un controllo sulla tabella privilege per vedere se può compiere quell'azione in quella determinata area o unit (come avviene normalmente in liquid). Un corretto provisioning è essenziale.

In partica, a differenza del normale "gui_preset" di Liquid, l'utente potrebbe non accorgersi mai della presenza delle "unit" dato che queste vengono selezionate per lui.

Questo ovviamente se ci sono alberature di unit separate per i vari gruppi...

**Comment by ralzakark** [comment]
...richiederebbe una ulteriore separazione degli alberi delle unit. Richiede più tempo in fase di configurazione (magari creando un altro template copy/paste per le unit) ma non dovremmo quasi toccare la logica interna di liquid potendo sfruttare la tabella privilege: 

``` sql
CREATE TABLE "privilege" (
        PRIMARY KEY ("unit_id", "member_id"),
        "unit_id"               INT4            REFERENCES "unit" ("id") ON DELETE CASCADE ON UPDATE CASCADE,
        "member_id"             INT4            REFERENCES "member" ("id") ON DELETE CASCADE ON UPDATE CASCADE,
        "admin_manager"         BOOLEAN         NOT NULL DEFAULT FALSE,
        "unit_manager"          BOOLEAN         NOT NULL DEFAULT FALSE,
        "area_manager"          BOOLEAN         NOT NULL DEFAULT FALSE,
        "member_manager"        BOOLEAN         NOT NULL DEFAULT FALSE,
        "initiative_right"      BOOLEAN         NOT NULL DEFAULT TRUE,
        "voting_right"          BOOLEAN         NOT NULL DEFAULT TRUE,
        "polling_right"         BOOLEAN         NOT NULL DEFAULT FALSE );
```

**Comment by EmanueleSabetta** [comment]
La terminologia è un poco confusa. Se ho capito quello che intendi le prime tre sarebbero:

Per ogni macro-unità (Es. Regione Lazio o comune Roma o Municipio VI):
Eletti -> Proposte Pubbliche degli Eletti M5S o Altri Gruppi Politici (proposte "dall'alto")
Cittadini -> Proposte Pubbliche dei Cittadini (proposte "dal basso")
Iscritti -> Proposte Interne Iscritti M5S

Ma la quarta? Non ho capito cosa intendi per M5S.

**Comment by ralzakark** [comment]
Errore mio.. correggo

**Comment by ralzakark** [comment]
Sempre ragionando a voce alta su questa ipotesi di divisione delle unit...
Se gli utenti possono sempre aprire proposte alternative (anche nell unit tree degli eletti, etc) allora il boolean "initiative_right" non basta più (pensavo che potevamo usare questo flag per determinare se un utente può creare una issue o meno). In tal caso potremmo aggiungere un ulteriore boolean ("issue_right") per risolvere la cosa ed evitare così logiche più complesse sull'authorship delle issue. Dovrei studiare meglio il codice di lua per vedere come sono implementati questi flag (della tabella privilege).

Le unit tree dei "cittadini",  degli "eletti", e degli "altri gruppi politici" sarebbero fondamentalmente tre alberi identici (con le medesime child unit e relative aree). Gli eletti potranno postare le issue in "eletti" e "altri gruppi". Ci potrebbero essere dei gruppi di utenti (tra cui possono far parte anche gli eletti) adibiti a postare le issue dei gruppi politici (e quindi avranno l'issue_right solo per "altri gruppi politici"). I cittadini ovviamente potranno aprire issue solo nello unit tree relativo.

**Comment by ralzakark** [comment]
Al livello 1 controlliamo se l'utente vuole entrare nella unit degli iscritti o meno (bottone "ASSEMBLEA INTERNA MOVIMENTO 5 STELLE LAZIO").
Al livello 2, se abbiamo scelto ASSEMBLEA REGIONE LAZIO, raffiniamo ulteriormente il selector delle unit scegliendo, a seconda del bottone premuto, l'albero giusto. (Nota: il livello 2 dell'ASSEMBLEA INTERNA in questo caso sarebbe ridondante per la selezione delle unit da visualizzare).
Possiamo creare delle root parent unit per distinguere le assemblee e per la selezione della unit basterebbe fare un filtro sul "parent_id" della unit (hardcoded nel myconfig ad esempio). I vari municipi di Roma potebbero essere appiattiti a livello delle altre città (se non lo sono già) in modo da facilitarne la gestione. 
L'unica selezione "esplicita" della unit, verrebbe fatta solo in fase di creazione di una nuova issue e solo per coloro che hanno diritto di creazione in più di una unit.

**Comment by ralzakark** [comment]
Pagina caricata su repo test.
La via di ricevere uno unit_selector non sembra praticabile.
La pagina prevede per ora che vengano passati o una "unit_id"  o un "areas_selector" pre-filtrato con le unit scelte ai livelli precedenti.
