### ISSUE TITLE
Design 3 UI  [Task C3] - Se si preme il bottone FILTRI, un'area si apre tra il il menu opzioni e la lista proposte, e compare un menu con tre tipi di filtri 

### ISSUE THREAD

**Issue by pierangelo** [Movimento5StelleLazio/ParlamentoElettronicoM5S#42]
assegnato

**Comment by pierangelo** [comment]
Ema mi occorrono chiarimenti sulla terza serie di filtri, quelli inerenti le unità: se stiamo lavorando sul "nascondere" il concetto di unità, per come la vedo io, la serie in questione non ha senso

**Comment by pierangelo** [comment]
inoltre anche alcuni filtri della seconda serie non sono chiari:   nella home io ho "i miei voti" e "le mie proposte".
ad esse che senso ha applicare un filtro "Potenzialmente Sostenute" ?

**Comment by EmanueleSabetta** [comment]
Infatti non si applica. Come ti dicevo alla riunione questa palette di filtri e' quella di base, ma poi a seconda della pagina devi visualizzare solo i filtri che hanno senso nel contesto.
Ad esempio il box "le mie proposte" visualizza le "Issue" create dall'utente o le Issue non create dall'utente ma in cui l'utente ha aggiunto una Initiative (proposta alternativa) sua. Ma non visualizza quelle sostenute o in cui ha fatto suggerimenti. Di conseguenza la distinzione tra sostenitore e sostenitore potenziale (che si differenziano in quanto il secondo e' un sostenitore con almeno un suggerimento in "deve" non implementato) non ha importanza. La avra' invece nelle sezioni di livello 5, dove sono elencate tutte le proposte di un area. Ma domani ti faccio uno schema.

**Comment by pierangelo** [comment]
:+1:

**Comment by ralzakark** [comment]
Che dite, si potrebbe lasciare visibile il bottone "APPLICA FILTRI" per collassare il menu? (Magari diventa "CHIUDI FILTRI"...)

**Comment by EmanueleSabetta** [comment]
Si, perfetto. Da APPLICA FILTRI potrebbe cambiare in ELIMINA FILTRI (così da far capire che non viene solo chiuso il riquadro ma vengono rimossi anche i filtri applicati e la pagina torna a visualizzare tutto senza filtri).

**Comment by EmanueleSabetta** [comment]
Ho uppato la tabella dei filtri:
https://github.com/Movimento5StelleLazio/ParlamentoElettronicoM5S/wiki/Design-9-UI-Tabella-FILTRI

**Comment by pierangelo** [comment]
:+1:
