### ISSUE TITLE
modifica bozza

### ISSUE THREAD

**Issue by ilbarillo2014** [Movimento5StelleLazio/ParlamentoElettronicoM5S#441]
selezionando "modifica bozza" per una proposta gia' inserita, appare solo lo step 1, dove e' possibile modificare il testo. Cliccando poi su avanti, si procede direttamente all'ultimo step, dove si puo' solo salvare e pubblicare.
Ho necessita' di modificare tutti i passaggi, compreso il link al video youtube.
grazie

**Comment by panseo** [comment]
Fixato
