### ISSUE TITLE
Design 5 Albero Pagine

### ISSUE THREAD

**Issue by ralzakark** [Movimento5StelleLazio/ParlamentoElettronicoM5S#50]
# Routing pagine:

Prima bozza routing pagine.

**Start Page - Livello 1**
- module = index
- view = _welcome

**Homepage - Livello 2**
- module = index
- view = homepage

**Scelta Aree - Livello 3**
- module = unit
- view = show_ext
- id = unit_id
- params = { filter_areas = "my_areas" } (opzionale)

**Operazioni nelle Aree - Livello 4**
- module = area
- view = filter
- id = area_id
- params = none

**Comment by EmanueleSabetta** [comment]
Una nota: ho rinominato anche nella wiki il Livello 4 da "Operazioni nelle Aree" a "Scelta delle Categorie di Proposte", che è meno ambiguo. Allineiamoci con la terminologia.
