### ISSUE TITLE
Design 9 UI Tabella FILTRI

### ISSUE THREAD

**Issue by ralzakark** [Movimento5StelleLazio/ParlamentoElettronicoM5S#55]
Per "Categoria 2: Proposte in Attualmente in Discussione" intendi le proposte che non sono chiuse o cancellate e non letteralmente le proposte in fase "discussion" , giusto? Altrimenti i filtri a livello 5 (Discussione, Congelato, Votazione e Commissione) non avrebbero senso...

**Comment by EmanueleSabetta** [comment]
Si, l'avevo scritto nella wiki:
https://github.com/Movimento5StelleLazio/ParlamentoElettronicoM5S/wiki/Design-8-UI-LISTA-PROPOSTE-SCELTE

Task H2 - Servire la pagina con la lista delle proposte ASSEMBLEA PUBBLICA LAZIO, PROPOSTE DEI CITTADINI nella **fase IN DISCUSSIONE (che include: in discussione, in votazione, in congelamento, in commissione e in voto su rapporto commissione).**

Riassumendo vi sono 3 macro fasi: 
Categoria 1 - fase IN CERCA DI SOSTENITORI (include: nuova)
Categoria 2 - fase IN DISCUSSIONE (include: in discussione, in votazione, in congelamento, in commissione e in voto su rapporto commissione).
Categoria 3 - fase COMPLETATE O RITIRATE (che include: chiuse o annullate).

**Comment by ralzakark** [comment]
Non riusciamo magari ad evitare di ripetere il termine? Potrebbe creare confusione la cosa.
Per la Categoria 2 si potrebbe usare "IN ESAME" al posto di "IN DISCUSSIONE" ad esempio...

**Comment by EmanueleSabetta** [comment]
Si, sarebbe una buona idea. Ma escluderei "IN ESAME" perché fa pensare all'esame delle commissioni o comunque ad un test di qualcosa di già definito. Invece deve esprimere anche la fase dialettica e propositiva. Fammi pensare...

**Comment by EmanueleSabetta** [comment]
IN SVOLGIMENTO
IN SVILUPPO
IN PROCEDIMENTO
IN CORSO
... direi "IN SVOLGIMENTO" suona meglio.

**Comment by EmanueleSabetta** [comment]
Ho aggiornato le wiki con "IN SVOLGIMENTO". L'unica cosa che non ho modificato è il testo del bottone del Livello 4, dove ho lasciato "IN DISCUSSIONE", ma in seguito se crea confusione lo modifichiamo.

**Comment by EmanueleSabetta** [comment]
Inoltre considera che la mappatura a livello semantico per l'utente sarà comunque cambiata secondo lo schema visto in Design UI4: https://github.com/Movimento5StelleLazio/ParlamentoElettronicoM5S/wiki/Design-4-UI-Box-Proposte

Le fasi sono così mappate:
originale -> nuova
1 - Nuova -> RICERCA SOSTENITORI
2 - Discussione -> EMENDAMENTI
3 - Verifica (congelamento) -> CONGELATA
4 - Votazione -> VOTAZIONE
5 - Verifica commissione (congelamenti commissione) -> IN COMMISSIONE 
6 - Votazione (del rapporto di commissioni) -> VOTAZIONE RAPPORTO COMMISSIONE 
7 - Terminata o Annullata -> FINE 

Quindi per l'utente la label "Discussione" non ci sarà mai, ma sarà sostituita da "Emendamenti". In questo senso non dovrebbe confondersi con il bottone.

**Comment by ralzakark** [comment]
:+1:

**Comment by ralzakark** [comment]
@Pierangelo:

La mia idea era questa. Potresti muovere i filtri sotto issue/_filters_ext.lua ed io poi li carico a livello 5 con:

``` lua
local filters = execute.load_chunk{module="issue", chunk="_filters_ext.lua", params = {
  member = member, state = state,  for_area = true...
}}
filters.content()
```

più o meno come avviene in LQ standard.
Se for_area == true allora mostri solo i filtri di livello 5 ed invece di richiamare la homepage chiami la mia pagina (area/show_ext per ora).

I valori per i filtri di stato ho messo questo:

``` lua
local issues_selector = area:get_reference_selector("issues")
if state == "open" then
  issues_desc = config.gui_preset.M5S.units[unit_name].issues_desc_open
  issues_selector:add_where("issue.state in ('admission', 'discussion', 'verification', 'voting')")
--  issues_selector:add_order_by("coalesce(issue.fully_frozen + issue.voting_time, issue.half_frozen + issue.verification_time, issue.accepted + issue.discussion_time, issue.created + issue.admission_time) - now()")

elseif state == "new" then
  issues_desc = config.gui_preset.M5S.units[unit_name].issues_desc_new
  issues_selector:add_where("issue.state = 'admission'")

elseif state == "development" then
  -- TODO issues_desc = config.gui_preset.M5S.units[unit_name].issues_desc_development
  issues_selector:add_where("issue.state in ('discussion', 'verification', 'voting')")

elseif state == "voting" then
  -- TODO issues_desc = config.gui_preset.M5S.units[unit_name].issues_desc_voting
  issues_selector:add_where("issue.state = 'voting'")

elseif state == "verification" then
  -- TODO issues_desc = config.gui_preset.M5S.units[unit_name].issues_desc_verification
  issues_selector:add_where("issue.state = 'verification'")

elseif state == "closed" then
  issues_desc = config.gui_preset.M5S.units[unit_name].issues_desc_closed_or_canceled
  issues_selector:add_where("issue.closed NOTNULL")
--  issues_selector:add_order_by("issue.closed "..ord)
end
```

**Comment by pierangelo** [comment]
1) la tua idea va bene ed e' conforme alla struttura dei tedeschi ma nella nostra  homepage abbiamo due liste di issues, situazione del tutto nuova in LQ.
il mio approccio astrae dalla presenza di n liste nella pagina:  la view dei filtri comunica solo l'intenzione di effettuare un'operazione e poi chi e' interessato la effettua.
E' un approccio orientato agli eventi, che consente un forte disaccoppiamento ed una conseguente facilità di utilizzo dei componenti in varie situazioni.
Attualmente credo sia molto dispendioso cercare di forzare il componente filters a gestire piu' liste contemporaneamente.

2) attento che la funzione execute.load_chunk e' deprecata

3) ecco la mia view filtri 

   --containerFiltri 

<PRE><code>
  execute.view{
        module="index" ,
        view="_filter_ext" , 
        params={ 
                level=2 ,
                category=category,
                module="index", 
                routing_page="homepage" 
                }
        }
</code></pre>

si limita solo ad indicare quale criterio applicare, poi i gestori delle singole liste si adeguano

**Comment by ralzakark** [comment]
1) Esatto, a me serve di sapere solo quale pulsante è stato premuto. La logica deve stare nella pagina chiamante della pagina filter. Quella della variabile "state" vorrebbe essere proprio un primo approccio a questo tipo di discorso. Ad. esempio dal livello 4 chiamo il livello 5 passando come parametro state = "new", "development" o "closed" corrispondenti ai 3 pulsanti "PR. IN CERCA DI SOSTENITORI", "PR. ATTUALMENTE IN DISCUSSIONE" e "PR. COMPLETATE O RITIRATE". A livello 5 se lo stato è "development" (categoria 2) i filtri dovranno mostrare altri pulsanti, quali "Discussione", "Congelato" e "Votazione" direttamente corrispondenti agli stati issue "discussion", "verification" e "voting". A livello 5 inoltre aggiungo anche un altro parametro orderby = "supporters", "last_event" o "creation_date" corrispondente al pulsante di ordinamento premuto. Nella pagina poi, a seconda della combinazione dei parametri (o pulsanti premuti, che dir si voglia), preparo la query corretta.
Magari ne riparliamo a voce...

2) Roger :+1: 

3) :+1:

**Comment by ralzakark** [comment]
Per quanto riguarda la logica ad eventi non ho capito bene cosa intendi... se i filtri devono essere intelligenti allora devono considerare tutti i vari stati/ordinamenti/filtri in modo da mostrare solo i pulsanti attinenti. Per questo la sezione filtri dovrebbe comunque avere la logica di una macchina a stati. Se ci affidiamo a logiche associate alle gui, quali livelli/categorie etc si rischia di generare confusione perché ci stiamo allontanando dalla "base dati".
Il livello 4 e 5 ad esempio vengono visti in LQ standard come una cosa sola, mentre noi invece filtriamo le issue in due livelli/view successive.

**Comment by ralzakark** [comment]
|Attualmente credo sia molto dispendioso cercare di forzare il componente filters a gestire piu' liste contemporaneamente.

Se intendi i vari ui.tab e ui.filters non contavo di usarli. Sui pulsanti metto dei semplici ui.link con il collegamento alla pagina stessa e passo nuovamente tutti i parametri che mi sono arrivati dalla GET.

**Comment by pierangelo** [comment]
Se ci affidiamo a logiche associate alle gui, quali livelli/categorie etc si rischia di generare confusione perché ci stiamo allontanando dalla "base dati"...e' proprio l'obiettivo del decoupling.

Comunque stiamo parlando della logica all'interno dell'architettura MVC che stiamo usando in Lq, non della logica di un componente intelligente. (inoltre c'e' differenza tra una View ed un Componente)
Per la precisione noi usiamo un pattern denominato "Mediator Pattern" e per farla breve e' del tutto legittimo passare quei tipi di dati che, all'interno del componente, vanno a determinare la tabella di transizione.
