### ISSUE TITLE
Task A9-10 - Strutture Dati

### ISSUE THREAD

**Issue by ralzakark** [Movimento5StelleLazio/ParlamentoElettronicoM5S#75]
### Questa è la struttura dati richiesta da design:

**Task A9** - DB TABLE "issue"
1.  Campo da aggiungere: "issue_full_title" (TITOLO QUESTIONE)
    Datatype: text
2.  Campo da aggiungere: "issue_brief_description" (DESCRIZIONE QUESTIONE )
    Datatype: text
3.  Campo da aggiungere: "issue_keywords" (PAROLE CHIAVE QUESTIONE )
    Datatype: text
4.  Campo da aggiungere: "issue_problem_description" (DESCRIZIONE PROBLEMA )
    Datatype: text
5.  Campo da aggiungere: "issue_target_description" (DESCRIZIONE OBIETTIVO )
    Datatype: text

**Task A10** - DB TABLE "initiative"
1.  Campo da aggiungere: "full_title" (TITOLO PROPOSTA)
    Datatype: text
2.  Campo da aggiungere: "brief_description" (DESCRIZIONE PROPOSTA )
    Datatype: text
3.  Campo da aggiungere: "competence_fields" (AREE DI COMPETENZA TECNICA)
    Datatype: text
4.  Campo da aggiungere: "authored_other_political_groups" (AVANZATA DA ALTRI GRUPPI POLITICI)   Datatype: boolean
### Issue:

``` SQL
ALTER TABLE issue ADD COLUMN title text;
COMMENT ON COLUMN issue.title IS 'Issue full title';
ALTER TABLE issue ADD COLUMN brief_description text;
COMMENT ON COLUMN issue.brief_description IS 'Brief description of the issue';
ALTER TABLE issue ADD COLUMN keywords tsvector;
COMMENT ON COLUMN issue.keywords IS 'Keyword provided by the author';
ALTER TABLE issue ADD COLUMN problem_description text;
COMMENT ON COLUMN issue.problem_description IS 'Description of the problem to be solved';
ALTER TABLE issue ADD COLUMN aim_description text;
COMMENT ON COLUMN issue.aim_description IS 'Description of the issue aim';
```
- keyword diventa un "tsvector"
### Initiative:

``` SQL
ALTER TABLE initiative ADD COLUMN title text;
COMMENT ON COLUMN initiative.title IS 'Initiative full title';
ALTER TABLE initiative ADD COLUMN brief_description text;
COMMENT ON COLUMN initiative.brief_description IS 'Brief description of the initiative';
ALTER TABLE initiative ADD COLUMN competence_fields text;
COMMENT ON COLUMN initiative.competence_fields IS 'Technical competence fields';
CREATE TYPE "author_type" AS ENUM ('elected', 'other');
ALTER TABLE initiative ADD COLUMN author_type author_type;
COMMENT ON COLUMN initiative.author_type IS 'Type of author';
```
- Per "competence_fields" per ora posso mettere "text" ma andrebbe creata una tabella "competence_fields" per incrociare l'initiative con una commissione tecnica. In caso ho già pronta la struttura dati per i nomi delle commissioni (con relativo pannello admin per la creazione ed il listing) 

``` SQL
CREATE TABLE "committee" (
                "id"            SERIAL4 PRIMARY KEY,
                "name"          TEXT NOT NULL DEFAULT ''::text, -- Committee description
                "description"   TEXT DEFAULT ''::text,
                "text_search_data" tsvector);
CREATE INDEX "committee_text_search_data_idx" ON "committee" USING gin ("text_search_data");
CREATE TRIGGER "update_text_search_data" BEFORE INSERT OR UPDATE ON "committee" FOR EACH ROW EXECUTE PROCEDURE tsvector_update_trigger('text_search_data', 'pg_catalog.simple', "name", "description");
COMMENT ON TABLE "committee" IS 'Committees formed to do research and make recommendations on a potential or planned project or change. ';
COMMENT ON COLUMN "committee"."name" IS 'Committee description';

CREATE TABLE "committee_request" (
        PRIMARY KEY ("committee_id", "member_id", "issue_id"),  
        "committee_id"  INT4 REFERENCES "committee" ("id") ON DELETE CASCADE ON UPDATE CASCADE, 
        "member_id"     INT4 REFERENCES "member" ("id") ON DELETE CASCADE ON UPDATE CASCADE,
        "issue_id"      INT4 REFERENCES "issue" ("id") ON DELETE CASCADE ON UPDATE CASCADE);
COMMENT ON TABLE "committee_request" IS 'Member committee request for an issue';
```
- Altra domanda: il campo di competenza sull'initiative è vincolante per la richiesta di una commissione tecnica o è solo un "consiglio" dell'autore (stessa questione che avevo sollevato riguardo il titolo e la descrizione) ?
- "authored_other_political_groups" diventa "author_type", un datatype ENUM. Questo dovrebbe essere valorizzato secondo i flag del member autore (per ora esiste il solo flag "elected" )

**Comment by EmanueleSabetta** [comment]
- il campo area di competenza e' solo un consiglio, non e' vincolante (mi pareva di averlo scritto)
- le aree di competenza sono da definire tramite un nuovo pannello admin che devo ancora postare nella wiki, e sono composte da un nome e un numero variabile di materie scientifiche associate ( che franno da filtro per la creazione della mailing list della commissione, come sara' chiaro appena postero' il design della fase delle commissioni ).
- si la sostituzione con un enum per authorship (=paternita')  va bene, aggiorna anche il design.

**Comment by ralzakark** [comment]
Link alla discussione sull'implementazione delle keyword:
https://github.com/Movimento5StelleLazio/ParlamentoElettronicoM5S/issues/166
