### ISSUE TITLE
Design 1 Strutture Dati - Task A4 - Creazione DB TABLE "template_areas".

### ISSUE THREAD

**Issue by ralzakark** [Movimento5StelleLazio/ParlamentoElettronicoM5S#8]
> 1. Campo da aggiungere: "area_id"

"area" ha un campo NOT NULL per "unit_id" con un relativo DELETE CASCADE sulla tabella "unit".

``` sql
CREATE TABLE "area" (
        "id"                    SERIAL4         PRIMARY KEY,
        "unit_id"               INT4            NOT NULL REFERENCES "unit" ("id") ON DELETE CASCADE ON UPDATE CASCADE,
        "active"                BOOLEAN         NOT NULL DEFAULT TRUE,
        "name"                  TEXT            NOT NULL,
        "description"           TEXT            NOT NULL DEFAULT '',
        "direct_member_count"   INT4,
        "member_weight"         INT4,
        "text_search_data"      TSVECTOR );
```

Un'area deve essere per forza associata alla relativa unit e viene automaticamente cancellata quando la sua unit viene eliminata.
E' necessario quindi creare delle unit di "appoggio" per le aree del template.
In questo caso, il campo al punto 3, potrebbe essere sostituito con "unit_id" (invece che "area_id").
La unit quindi diventa una "template unit" quando gli si screa un template "addosso".
Il template può essere creato o eliminato a piacere da una unit e la unit può essere usata anche se è un template.
Si potrebbe implementare un controllo (o una checkbox sul template) per evitare che i membri possano avere diritti di voto sulla unit di appoggio (tramite la tabella "privilege").

Volendo invece creare un vero e proprio template come descritto sopra, sarebbe forse meglio creare un'apposita tabella per le aree che formano il template.
Si rimuoverebbero i campi "unit_id" (quindi nessuna necessità di associare all'area una unit esistente) e altri campi inutili quali  "active" , "direct_member_count, etc..
Queste sarebbero delle "skeleton" area che saranno poi trasformate in vere e proprie aree all'interno delle varie unit quando il template viene incollato.

Data la flessibilità e la più facile implementazione io opterei per la prima ipotesi.

**Comment by EmanueleSabetta** [comment]
Mi sembra più modulare la seconda idea invece. Isolerebbe il template come oggetto indipendente e renderebbe più snelle le aree associate (niente active flags, member count, weight, text search da indicizzare, etc.) che diverrebbero effettivamente solo scheletri base.
Creiamo una table chiamata "template_area" che è come "area" ma con solo i campi "id, name, description".
Gli area_id dovranno essere quindi diversi dai template_area_id e indipendenti. Sarà però necessario duplicare la table "allowed_policy" creandone una chiamata "template_allowed_policy", i cui area_id saranno sostituiti dalla template_area_id. Che ne dici?

**Comment by ralzakark** [comment]
OK, è sicuramente la soluzione più pulita :+1: 

Quindi le tabelle potrebbero essere:
- template (id, name, description) - Contiene i nomi e le descrizioni dei template
- skeleton_area (id, name, description) - Contiene le skeleton delle aree
- skeleton_area_allowed_policy (skeleton_area_id, policy_id, default_policy) - Associa le policy alle aree skeleton
- template_area (template_id, skeleton_area_id) - Associa i template alle aree skeleton.

Se ti va bene metto in wiki.

**Comment by ralzakark** [comment]
In realtà, a differenza della relazione unit <-> area che è m = m, la relazione template <-> skeleton_area è 1 = m.
Quindi la tabella template_area scompare...
Rinominandole di nuovo abbiamo:
- template (id, name, description) - Contiene i nomi e le descrizioni dei template
- template_area (template_id, name, description) - Contiene le skeleton area 
- template_area_allowed_policy (skeleton_area_id, policy_id, default_policy) - Associa le policy alle  skeleton area

**Comment by EmanueleSabetta** [comment]
Si, anche se sarebbe meglio chiamare le skeleton_area "template_area" o "area_template". La parola "skeleton" introduce una distinzione semantica in realtà inutile. Di fatto la skeleton_area è il template di un'area, giusto?

La relazione unit<->area è 1:1 comunque, se ho capito quello che dici. In ogni entry della tabella area c'è solo un campo unit_id INT4, giusto?
Quella template<->area_template è invece 1:molti, in quanto un template è un insieme di aree_template, ma ogni area_template appartiene solo ad un template. Si potrebbe in teoria usare una relazione m:m, ma questo limiterebbe molto l'editing in quanto in tal caso modificare un area_template in un template cambierebbe anche quell'area_template in tutti i template.

Quindi riassumendo:

template (id, name, description)
area_template (id, name, description, template_id) - ogni area_template punta ad un solo template
template_area_allowed_policy (area_template_id, policy_id, default_policy) - Associa le policy alle skeleton area

Aggiorniamo la wiki con i task struttura dati di queste tabelle.

**Comment by ralzakark** [comment]
> Si, anche se sarebbe meglio chiamare le skeleton_area "template_area" o "area_template". La parola "skeleton" >introduce una distinzione semantica in realtà inutile. Di fatto la skeleton_area è il template di un'area, giusto?

Giusto, avevo già aggiornato il wiki di conseguenza....

> La relazione unit<->area è 1:1 comunque

Ho ricontrollato... non è né 1:1 né m:m,  ma 1:m. Il discorso non cambia cmq.. la struttura va bene come avevi scritto al secondo post.

> Quella template<->area_template è invece 1:molti, in quanto un template è un insieme di aree_template, ma >ogni area_template appartiene solo ad un template. Si potrebbe in teoria usare una relazione m:m, ma questo >limiterebbe molto l'editing in quanto in tal caso modificare un area_template in un template cambierebbe anche >quell'area_template in tutti i template.

Stessa cosa che avevo pensato anche io....

> Aggiorniamo la wiki con i task struttura dati di queste tabelle.

Già fatto
