### ISSUE TITLE
Task D1 - Design 4 UI Box Proposte

### ISSUE THREAD

**Issue by ralzakark** [Movimento5StelleLazio/ParlamentoElettronicoM5S#84]
Assegnato

**Comment by ralzakark** [comment]
Ho un problemino con l'immagine "congelamento.svg".. occupa quasi un megabyte ed il browser non me la mostra.
Edit: Ho provato a ridurre il bitmap dentro l'svg con inkscape (1MB -> 71kb) ma il comportamento è lo stesso: quando provo a caricare la pagina l'svg non si vede, se punto il browser direttamente all'url statica dell'immagine (/lf/static/svg/verification.svg) il browser la cacha e poi me la mostra correttamente.

**Comment by ralzakark** [comment]
Va inserito il nuovo svg senza la freccia e con i nuovi colori.

**Comment by gogolander** [comment]
@panseo è stata più risolta questa?
