### ISSUE TITLE
Varie

### ISSUE THREAD

**Issue by ralzakark** [Movimento5StelleLazio/ParlamentoElettronicoM5S#9]
DOMANDE:
1. Commissioni: La commissione tecnica può essere richiesta anche in fase di discussione o solo in fase di verifica (io escluderei accettazione e votazione)?

BASE DATI:
2. Tabella member - Campo "codice_fiscale": trasformare da varchar(16) in TEXT e chiamarlo "nid" (national identification number) per internazionalizzarlo? http://en.wikipedia.org/wiki/National_identification_number
3. Tabella member - Campo "elected": esiste un eletto senza unità? se no, rimuovere flag e utilizzare la sola tabella unit_elected (member_id,unit_id)?
4. Tabella template: Scegliere modalità: a) tabella template (id, unit_id, name, description) b) flag sulla unit c) si copiano direttamente le unit d) tabella nativa con skeleton area (vorrei discuterla in riunione) -> RISOLTA

DATATYPE:
5. Tabella member - Chiavi e certificati: usato BYTEA come datatype per poter poi utilizzare le funzioni pgcrypto di Postgres.
6. Tabella member - Campo "PEC_public_key": E' un certificato o una chiave vera e propria?

STANDARD:
7. Tabella template_areas: Qualora utilizzata la tabella dovrebbe avere sempre un nome al singolare.
8. Tabella member - Campo "m5s_id": il suffisso "_id" è fuorviante, non c'è una tabella m5s, rinominato come "m5sid".
9. Tabella member - Campo "PEC_public_key": I campi dovrebbero essere tutti lowercase.

TODO:
10. Definire nomenclatura per le patch sql. Esempio: core-patch_v2.2.1-m5s2.2.1-0.1.sql ?
11. Defenire standard per le pull request. Chi fa la pull request la accetta anche sul repo o ci sarà un supervisore?

IDEE VARIE LIQUIDROID:
12. QRCODE: Generazione automatica di un QRCODE per le issue visualizzabili poi su schermi, flyers, tshirt etc..
13. Coordinate: Generazione automatica mappa su Google Maps, Realtà Aumentata da Google Glass, etc..

**Comment by EmanueleSabetta** [comment]
> DOMANDE:
> 1. Commissioni: La commissione tecnica può essere richiesta anche in fase di discussione o solo in fase di >verifica (io escluderei accettazione e votazione)?

La commissione tecnica può essere richiesta in fase di discussione e di verifica semplicemente aggiungendosi ai sostenitori della necessità di commissione tecnica. E' possibile richiedere una sola volta una commissione di ogni tipo per ogni fase. Ad esempio: se si richiede una commissione "chimica" nella fase discussione, non si può più richiederla nella stessa fase. Ma nella fase verifica si può richiedere di nuovo, in quanto significa che o non la si è chiesta prima o non si è soddisfatti del lavoro della commissione. Inoltre c'è una fase apposita prima del congelamento che viene inserita se si è raggiunto il quorum della commissione, che è appunto una fase in cui si lascia lavorare la commissione. Questa fase esiste prima del primo congelamento e prima del secondo congelamento (che viene attivato solamente se è stata richiesta una nuova commissione).
Comunque la cosa sarà più chiara quando avrò postato il design delle commissioni nella wiki.

> BASE DATI:
> 2. Tabella member - Campo "codice_fiscale": trasformare da varchar(16) in TEXT e chiamarlo "nid" (national >identification number) per internazionalizzarlo? http://en.wikipedia.org/wiki/National_identification_number

Sarebbe intelligente, ma riduce un poco la sicurezza. Sarebbe meglio aggiungere un campo ulteriore per il NIN, e un settaggio di configurazione per usare il campo CF o NIN.

> 1. Tabella member - Campo "elected": esiste un eletto senza unità? se no, rimuovere flag e utilizzare la sola >tabella unit_elected (member_id,unit_id)?

si, esistono eletti senza unità. Essere eletti o no è una caratteristica del member propria. Chi crea una unità può scegliere accessibile in scrittura agli eletti di una data circoscrizione o comune, ma a volte l'unità di quella circoscrizione o comune non esiste ancora o non è stata creata per quel comune o municipio. O viceversa è l'eletto che non è più in carica in un certo posto, ma non è ancora stato eletto in uno nuovo.

> DATATYPE:
> 5. Tabella member - Chiavi e certificati: usato BYTEA come datatype per poter poi utilizzare le funzioni pgcrypto >di Postgres.

ottimo

> 1. Tabella member - Campo "PEC_public_key": E' un certificato o una chiave vera e propria?

Questo servirebbe per i cittadini all'estero. In teoria penso di sostituirlo con la chiave pubblica della firma digitale, perché la gestione PEC autonoma ho visto che è troppo complessa e poco pratica. Cambialo in "pgp_public_key".

> STANDARD:
> 7. Tabella template_areas: Qualora utilizzata la tabella dovrebbe avere sempre un nome al singolare.

Si, e come ho detto "area_template" mi sembra ottimo (evidenzia che è un area).

> 1. Tabella member - Campo "m5s_id": il suffisso "_id" è fuorviante, non c'è una tabella m5s, rinominato come >"m5sid".

ok

> 1. Tabella member - Campo "PEC_public_key": I campi dovrebbero essere tutti lowercase.

si, come ho detto cambialo in "pgp_public_key".

> TODO:
> 10. Definire nomenclatura per le patch sql. Esempio: core-patch_v2.2.1-m5s2.2.1-0.1.sql ?

Si va bene. Poi comunque dovremo vedere come fare a proporre il merge ai tedeschi.

> 1. Defenire standard per le pull request. Chi fa la pull request la accetta anche sul repo o ci sarà un >supervisore?

Chi accetta la richiesta di pull deve testare prima tutto nel suo branch di test (in locale o sul server sviluppo), e solo se va bene acconsentire al merge. In teoria dovrebbe essere una persona diversa da chi richiede il pull perché chi ha causato un bug difficilmente riesce a vederlo, serve sempre un'altra persona.
Ma al momento siamo in una fase troppo preliminare e siamo in pochi (chiedi magari a Pierangelo di aiutarti quando ci sono grossi diff). L'importante è aver testato a fondo il merge in locale o sul server sviluppo, e se si trovano problemi ripristinare immediatamente la versione precedente.

> IDEE VARIE LIQUIDROID:
> 12. QRCODE: Generazione automatica di un QRCODE per le issue visualizzabili poi su schermi, flyers, tshirt >etc..

Ottima idea. Basta puntare il cellulare sul manifesto / volantino e la app Liquidroid decodifica il QRCode tramite la camera e apre la Issue corrispondente nella app.

> 1. Coordinate: Generazione automatica mappa su Google Maps, Realtà Aumentata da Google Glass, etc..

Questa non mi è chiara. A che serve la mappa?

**Comment by ralzakark** [comment]
> > Tabella member - Campo "PEC_public_key": I campi dovrebbero essere tutti lowercase.
> 
> si, come ho detto cambialo in "pgp_public_key".

Ho già inserito nel branch di test una rsa_public_key, la sopracitata è parallela o sovrascrive quest'ultima?

> > Coordinate: Generazione automatica mappa su Google Maps, Realtà Aumentata da Google Glass, etc..
> 
> Questa non mi è chiara. A che serve la mappa?

A ogni issue potrebbero essere associate delle coordinate, cliccando sull'iconcina a forma di mappa si aprirebbe un link (autogenerato a partire dalle coordinate) su gmail con vista satellite... Se ad esempio c'è una issue per costruire una nuova centrale a carbone l'utente può facilmente vedere sulla mappa i dintorni del luogo di costruzione e si accorge che proprio li vicino c'è un parco storico!....o ancora, passeggiando vicino ad un parco tenuto in cattive condizioni l'utente vede una issue attraverso i suoi Google Glass che propone una ristrutturazione, essendo sul posto può verificare di persona le condizioni e prendere una decisione più oculata.

**Comment by EmanueleSabetta** [comment]
Per la key: Si, è la stessa. Lasciane una sola.

Per la mappa: è una buona idea, ma rischiosa per la sicurezza. Più facile inserire nel testo un link a google maps.
