### ISSUE TITLE
Design 4 UI Box Proposte

### ISSUE THREAD

**Issue by ralzakark** [Movimento5StelleLazio/ParlamentoElettronicoM5S#99]
L'overflow a scroll per le proposte potrebbe essere problematico per schermi touch di piccole dimensioni. Possiamo trovare un'alternativa ?
Es. Mostrare solo N proposte e aggiungere una dicitura "Altre 123 proposte non visualizzate. Clicca su VEDI DETTAGLI per visualizzarle tutte"

**Comment by EmanueleSabetta** [comment]
Che intendi? Ti riferisci alla dimensione della barra di scorrimento? Sui dispositivi touch non si usa, ma si trascina il contenuto.
Per esempio qui su iPhone con il dito scorro il testo trascinandolo direttamente, senza vedere la barra:
http://webdesign.about.com/od/examples/l/bl-overflow-x-and-overflow-y-examples.htm#y-scroll
O forse ti riferisci ad un problema con i div interni? Vi sono librerie tipo fleXcroll che aggirano il problema: http://www.hesido.com/web.php?page=customscrollbar 
Puoi farmi vedere un esempio di quello che intendi, così la testo su iphone?

Comunque ti anticipo che sono d'accordo nell'usare un sistema di caricamento standard, seppure di 20 elementi alla volta. Liquid ha già un bottone tipo "More..." che dice "Altre 123 proposte non visualizzate. Clicca per caricarne altre.", e ogni volta che lo premi se ne caricano altre. Per me andrebbe bene usarlo per le proposte, che sono in fondo, ma per i testi delle descrizioni è necessario incasellarli vicini per non confondere l'utente con pagine di testo troppo lunghe che gli fanno perdere l'orientamento nell'interfaccia. 

P.S.
Dai un occhiata anche ad iScroll, che simula lo scrolling touch sui dispositivi mobile anche senza usare funzioni che usano chiamate native tipo "-webkit-overflow-scrolling:touch" :  http://cubiq.org/iscroll-4

**Comment by ralzakark** [comment]
Quando si fa lo scroll delle issue via touch screen, se tocchi il contenuto del div interno (quello con l'elenco delle proposte) ti scrolla queste ultime invece che le proposte. Bisogna quindi andare a toccare la parte esterna al div.
Personalmente è una cosa che trovo abbastanza fastidiosa su alcuni siti. Mentre scrollo ad un certo punto si blocca e comincia a scrollare il sub div... ora sinceramente non so farti un esempio.

**Comment by EmanueleSabetta** [comment]
Si è vero, ma di solito si usano due modi per risolvere la cosa:
1) lasciare un bordo sufficientemente grande a destra e sinistra della scrollbox. Diciamo grande come un polpastrello.
2) fare in modo che la scrollbox abbia una height sempre minore della height della finestra del browser, in modo da avere sempre almeno un dito di spazio sopra o sotto, qualunque sia la posizione della scrollbox.

**Comment by EmanueleSabetta** [comment]
Comunque valuta tu l'implementazione, poi la proviamo insieme. Per il 14 qualunque cosa va bene, basta che funzoni. Dai comunque un occhiata al demo pull-to-refresh di iScroll4: http://cubiq.org/dropbox/iscroll4/examples/pull-to-refresh/
Prova a metterlo in un riquadro che si dimensiona verticalmente per essere più piccolo in height della finestra web.

**Comment by ralzakark** [comment]
Il problema si presenta soprattutto quando faccio lo zoom (ad esempio per leggere meglio i titoli delle proposte)... non vedrò più i bordi (almeno quello di dx) e il div delle proposte mi occuperà tutto lo schermo.
Se trovo una issue con molte proposte devo fare zoom out, scrollare il main div e rifare zoom in... diventa fastidioso.

**Comment by EmanueleSabetta** [comment]
Vero, ma: 
1) I titoli delle proposte devono essere comunque in un font grande di default, quindi devono essere leggibili senza ricorrere al pinch-to-zoom
2) se usiamo iScroll4 possiamo superare il problema usando la funzione di zoom interna alla scrollbox, come in questo demo: http://cubiq.org/dropbox/iscroll4/examples/zoom/

**Comment by ralzakark** [comment]
ok
